const recipes = [
  {
    id: 1,
    name: 'Omelette',
    image: 'img/omelette.jpg',
    category: 'Lunch',
    price: 10,
    description: 'lorem ipsum ascum lorem tropen sorem',
  },
  {
    id: 2,
    name: 'Grilled chicken',
    image: 'img/chicken.jpg',
    category: 'Lunch',
    price: 8,
    description: 'lorem ipsum ascum lorem tropen sorem',
  },
  {
    id: 3,
    name: 'Stew',
    image: 'img/stew.jpg',
    category: 'Lunch',
    price: 12,
    description: 'lorem ipsum ascum lorem tropen sorem',
  },
  {
    id: 4,
    name: 'Pzza',
    image: 'img/pizza.jpg',
    category: 'Lunch',
    price: 8,
    description: 'lorem ipsum ascum lorem tropen sorem',
  },
  {
    id: 5,
    name: 'Straberry Shake',
    image: 'img/strawberry.jpg',
    category: 'Shakes',
    price: 5,
    description: 'lorem ipsum ascum lorem tropen sorem',
  },
  {
    id: 6,
    name: 'Gooseberries Shake',
    image: 'img/gooseberries-shake.jpg',
    category: 'Shakes',
    price: 5,
    description: 'lorem ipsum ascum lorem tropen sorem',
  },
  {
    id: 7,
    name: 'Pancakes',
    image: 'img/pancakes.jpg',
    category: 'Lunch',
    price: 6,
    description: 'lorem ipsum ascum lorem tropen sorem',
  },
  {
    id: 8,
    name: 'Pudding',
    image: 'img/pudding.jpg',
    category: 'Breakfast',
    price: 3,
    description: 'lorem ipsum ascum lorem tropen sorem',
  },
  {
    id: 9,
    name: 'Rice Pudding',
    image: 'img/rice-pudding.jpg',
    category: 'Breakfast',
    price: 3,
    description: 'lorem ipsum ascum lorem tropen sorem',
  },
  {
    id: 10,
    name: 'Green Shake',
    image: 'img/green-shake.jpg',
    category: 'Shakes',
    price: 5,
    description: 'lorem ipsum ascum lorem tropen sorem',
  },
];

export default recipes;
